name: G@briel
favicon: null
layout_spectrum: 0.5244092002976686
typography_spectrum: 0.04835735005326569
title: test 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9867807407863438
  lightness: 0.48775915591977537
  saturation: 0.35335747874341905
  rhythmicContrast: 0.9946385361254215
purpose: []
